import { useState, useMemo } from 'react'
import { useFlow } from '../FlowProvider'
import { SuggestionCard } from '../SuggestionCard'
import { KeyboardHint } from '../KeyboardHint'
import { ConfirmButton } from '../ConfirmButton'
import { CheckCircle, Clock, Pill, AlertCircle, Loader2 } from 'lucide-react'

/**
 * ProcedureSuggestion Interface
 *
 * Represents an AI-suggested procedure based on patient context.
 * These suggestions come from the Claude AI engine analyzing:
 * - Patient's scheduled appointments from Epic
 * - Active diagnoses and treatment history
 * - Payer-specific billing patterns
 * - Historical claim data for similar patients
 */
interface ProcedureSuggestion {
  // CPT/HCPCS code for the procedure (e.g., '96413' for chemo infusion)
  cptCode: string
  // Human-readable procedure description
  description: string
  // Clinical category for grouping (e.g., 'Oncology', 'Cardiology')
  category: string
  // HCPCS J-code for administered drug (if applicable)
  drugCode?: string
  // Drug trade name for display (e.g., 'Pembrolizumab (Keytruda)')
  drugName?: string
  // Number of units (typically 1 for procedures, variable for drugs)
  units: number
  // Charge amount in cents for accurate calculations
  charge: number
  // AI confidence score (0-1) based on patient context match
  confidence: number
  // Suggested modifiers with requirement flags
  modifiers: Array<{
    code: string        // Modifier code (e.g., 'JW', '59', '25')
    description: string // Human-readable description
    required: boolean   // Whether modifier is required for clean claim
  }>
}

/**
 * Step 2: Procedure Select
 *
 * Displays AI-suggested procedures based on patient context from Epic.
 * Suggestions are generated by analyzing:
 * - Scheduled appointments and treatment plans
 * - Patient's active diagnoses
 * - Historical billing patterns
 * - Payer-specific requirements
 *
 * DATA FLOW:
 * 1. Patient data loaded in Step 1 triggers procedure suggestion API
 * 2. Claude AI analyzes patient context and Epic schedule data
 * 3. Suggestions returned with confidence scores and required modifiers
 * 4. User selects procedure and applicable modifiers
 * 5. Selection stored in context for subsequent steps
 *
 * Matches: 09_agentic_procedure_suggest.svg
 */
export function ProcedureSelect() {
  const { context, selectProcedure, goBack, isLoading } = useFlow()
  const [selected, setSelected] = useState<ProcedureSuggestion | null>(null)
  const [selectedModifiers, setSelectedModifiers] = useState<string[]>([])

  /**
   * Transform context.suggestedProcedures to ProcedureSuggestion format.
   *
   * The suggestedProcedures come from the agentic engine which integrates:
   * - Epic FHIR Appointment and CarePlan resources
   * - Claude AI procedure prediction based on patient context
   * - Historical billing data for accuracy scoring
   *
   * NOTE: In production, suggestedProcedures are populated by the
   * procedure suggestion service when patient context is loaded.
   */
  const suggestions: ProcedureSuggestion[] = useMemo(() => {
    // Map from context's Procedure type to UI's ProcedureSuggestion type
    // The context stores the core procedure data; UI adds display metadata
    return (context.suggestedProcedures || []).map((proc, index) => ({
      cptCode: proc.cptCode,
      description: proc.description,
      // Category derived from CPT code prefix or mapped from procedure database
      category: getCategoryFromCptCode(proc.cptCode),
      drugCode: proc.drugCode,
      // Drug name would come from drug database lookup in production
      drugName: proc.drugCode ? getDrugNameFromCode(proc.drugCode) : undefined,
      units: proc.units,
      charge: proc.charge,
      // Confidence score from AI; first suggestion typically highest confidence
      confidence: 0.95 - (index * 0.05),
      // Modifiers from procedure with required flags based on payer rules
      modifiers: (proc.modifiers || []).map(code => ({
        code,
        description: getModifierDescription(code),
        // Required modifiers determined by payer-specific rules
        required: isModifierRequired(code, proc.cptCode),
      })),
    }))
  }, [context.suggestedProcedures])

  const handleSelect = (procedure: ProcedureSuggestion) => {
    setSelected(procedure)
    // Auto-select required modifiers
    const requiredMods = procedure.modifiers
      .filter((m) => m.required)
      .map((m) => m.code)
    setSelectedModifiers(requiredMods)
  }

  const handleConfirm = () => {
    if (!selected) return

    selectProcedure({
      cptCode: selected.cptCode,
      cptDescription: selected.description,
      drugCode: selected.drugCode,
      drugUnits: selected.units,
      units: selected.units,
      charge: selected.charge,
      modifiers: selectedModifiers,
    })
  }

  const toggleModifier = (code: string) => {
    setSelectedModifiers((prev) =>
      prev.includes(code)
        ? prev.filter((m) => m !== code)
        : [...prev, code]
    )
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h3 className="font-heading text-lg font-semibold text-neutral-900">
            Select Procedure
          </h3>
          <p className="text-body-sm text-neutral-500">
            AI-suggested based on scheduled treatment for{' '}
            {context.patient?.firstName}
          </p>
        </div>
        <KeyboardHint />
      </div>

      {/* Loading State */}
      {isLoading && (
        <div className="flex flex-col items-center justify-center py-12">
          <Loader2 className="h-12 w-12 animate-spin text-primary-600" />
          <p className="mt-4 text-neutral-600">Loading procedure suggestions...</p>
        </div>
      )}

      {/* Empty State - No suggestions available */}
      {!isLoading && suggestions.length === 0 && (
        <div className="rounded-xl border-2 border-dashed border-neutral-200 bg-neutral-50 p-8 text-center">
          <AlertCircle className="mx-auto h-12 w-12 text-neutral-400" />
          <h4 className="mt-4 font-heading text-lg font-semibold text-neutral-700">
            No Procedure Suggestions Available
          </h4>
          <p className="mt-2 text-neutral-500">
            Unable to suggest procedures for this patient. This may occur when:
          </p>
          <ul className="mt-3 text-left text-sm text-neutral-500 max-w-md mx-auto space-y-1">
            <li>- No scheduled appointments found in Epic</li>
            <li>- Patient context is insufficient for AI prediction</li>
            <li>- EHR integration is temporarily unavailable</li>
          </ul>
          <p className="mt-4 text-sm text-neutral-600">
            Please verify the patient has scheduled services or manually enter procedure codes.
          </p>
        </div>
      )}

      {/* Suggestion Cards - Rendered from context.suggestedProcedures */}
      <div className="space-y-3">
        {suggestions.map((procedure, idx) => (
          <SuggestionCard
            key={procedure.cptCode}
            selected={selected?.cptCode === procedure.cptCode}
            onClick={() => handleSelect(procedure)}
            tabIndex={idx + 1}
          >
            <div className="flex items-start justify-between">
              <div className="flex-1">
                <div className="flex items-center gap-3">
                  <span className="code text-lg font-semibold text-neutral-900">
                    {procedure.cptCode}
                  </span>
                  <span className="rounded-md bg-neutral-100 px-2 py-0.5 text-xs text-neutral-600">
                    {procedure.category}
                  </span>
                  {procedure.confidence >= 0.9 && (
                    <span className="flex items-center gap-1 rounded-md bg-success-100 px-2 py-0.5 text-xs text-success-700">
                      <CheckCircle className="h-3 w-3" />
                      Best match
                    </span>
                  )}
                </div>
                <p className="mt-1 text-neutral-700">{procedure.description}</p>

                {/* Drug info */}
                {procedure.drugCode && (
                  <div className="mt-3 flex items-center gap-2 rounded-lg bg-blue-50 px-3 py-2">
                    <Pill className="h-4 w-4 text-blue-600" />
                    <span className="code text-body-sm text-blue-700">
                      {procedure.drugCode}
                    </span>
                    <span className="text-body-sm text-blue-700">
                      {procedure.drugName}
                    </span>
                  </div>
                )}
              </div>

              <div className="text-right">
                <p className="font-semibold text-neutral-900">
                  ${procedure.charge.toLocaleString()}
                </p>
                <p className="text-body-sm text-neutral-500">
                  {procedure.units} unit{procedure.units > 1 ? 's' : ''}
                </p>
              </div>
            </div>

            {/* Modifiers (shown when selected) */}
            {selected?.cptCode === procedure.cptCode && procedure.modifiers.length > 0 && (
              <div className="mt-4 border-t border-neutral-200 pt-4">
                <p className="mb-2 text-body-sm font-medium text-neutral-700">
                  Suggested Modifiers
                </p>
                <div className="flex flex-wrap gap-2">
                  {procedure.modifiers.map((mod) => (
                    <button
                      key={mod.code}
                      onClick={(e) => {
                        e.stopPropagation()
                        toggleModifier(mod.code)
                      }}
                      className={`flex items-center gap-2 rounded-lg border px-3 py-2 transition-colors ${
                        selectedModifiers.includes(mod.code)
                          ? 'border-primary-500 bg-primary-50 text-primary-700'
                          : 'border-neutral-200 bg-white text-neutral-600 hover:border-neutral-300'
                      }`}
                    >
                      <span className="code font-medium">{mod.code}</span>
                      <span className="text-body-sm">{mod.description}</span>
                      {mod.required && (
                        <span className="text-xs text-warning-600">(Required)</span>
                      )}
                    </button>
                  ))}
                </div>
              </div>
            )}
          </SuggestionCard>
        ))}
      </div>

      {/* Schedule Context Info
          Displays the source of procedure suggestions to build user confidence.
          In production, this shows actual appointment data from Epic FHIR. */}
      {suggestions.length > 0 && (
        <div className="flex items-center gap-2 rounded-lg bg-neutral-100 px-4 py-3 text-body-sm text-neutral-600">
          <Clock className="h-4 w-4" />
          <span>
            Suggestions based on {context.patient?.firstName}'s scheduled appointments and treatment history
          </span>
        </div>
      )}

      {/* Actions */}
      <div className="flex items-center justify-between pt-4">
        <button
          onClick={goBack}
          className="rounded-lg border border-neutral-200 bg-white px-6 py-3 text-neutral-600 hover:bg-neutral-50"
        >
          Back
        </button>

        <ConfirmButton onClick={handleConfirm} disabled={!selected || isLoading}>
          Continue
        </ConfirmButton>
      </div>
    </div>
  )
}

/**
 * Helper Functions for Procedure Display
 *
 * These functions provide display metadata for procedures.
 * In a full production implementation, these would query:
 * - CPT/HCPCS code database for categories
 * - FDA NDC database for drug names
 * - CMS modifier definitions
 * - Payer-specific modifier requirements
 */

/**
 * Derives clinical category from CPT code prefix.
 *
 * CPT codes are organized by category:
 * - 99xxx: Evaluation & Management
 * - 96xxx: Infusion/Injection procedures
 * - 77xxx: Radiation oncology
 * - 36xxx: Cardiovascular procedures
 *
 * In production, this would query a comprehensive CPT database.
 */
function getCategoryFromCptCode(cptCode: string): string {
  // CPT code category mapping based on AMA CPT code structure
  const prefix = cptCode.substring(0, 2)

  const categoryMap: Record<string, string> = {
    // Evaluation and Management (99201-99499)
    '99': 'E&M',
    // Anesthesia (00100-01999)
    '00': 'Anesthesia',
    '01': 'Anesthesia',
    // Surgery - Integumentary (10000-19999)
    '10': 'Surgery - Integumentary',
    '11': 'Surgery - Integumentary',
    // Surgery - Cardiovascular (33000-37799)
    '33': 'Cardiovascular',
    '36': 'Cardiovascular',
    '37': 'Cardiovascular',
    // Radiology (70000-79999)
    '70': 'Radiology',
    '71': 'Radiology',
    '72': 'Radiology',
    '73': 'Radiology',
    '74': 'Radiology',
    '76': 'Radiology',
    '77': 'Radiation Oncology',
    '78': 'Nuclear Medicine',
    '79': 'Nuclear Medicine',
    // Pathology and Laboratory (80000-89999)
    '80': 'Pathology/Lab',
    '81': 'Pathology/Lab',
    '82': 'Pathology/Lab',
    '83': 'Pathology/Lab',
    '84': 'Pathology/Lab',
    '85': 'Pathology/Lab',
    '86': 'Pathology/Lab',
    '87': 'Pathology/Lab',
    '88': 'Pathology/Lab',
    '89': 'Pathology/Lab',
    // Medicine - Infusion/Injection (96360-96549)
    '96': 'Oncology',
    // Medicine - Psychiatry (90000-90899)
    '90': 'Psychiatry/Immunization',
    // Medicine - Dialysis (90935-90999)
    '91': 'Dialysis',
    // Medicine - Ophthalmology (92000-92499)
    '92': 'Ophthalmology',
    // Medicine - Cardiovascular (93000-93799)
    '93': 'Cardiovascular',
    // Medicine - Pulmonary (94000-94799)
    '94': 'Pulmonary',
    // Medicine - Neurology (95000-95999)
    '95': 'Neurology',
    // Physical Medicine (97000-97799)
    '97': 'Physical Medicine',
  }

  // HCPCS Level II codes (J-codes for drugs, etc.)
  if (cptCode.startsWith('J')) {
    return 'Drug Administration'
  }

  return categoryMap[prefix] || 'General'
}

/**
 * Retrieves drug trade name from HCPCS J-code.
 *
 * HCPCS Level II J-codes identify specific drugs:
 * - J9xxx: Chemotherapy drugs
 * - J0xxx-J8xxx: Other injectable drugs
 *
 * In production, this would query the FDA NDC database or
 * a comprehensive drug formulary database.
 */
function getDrugNameFromCode(drugCode: string): string {
  // Common oncology and specialty drug mappings
  // In production, this would be a database lookup
  const drugMap: Record<string, string> = {
    // Oncology - Immunotherapy
    'J9271': 'Pembrolizumab (Keytruda)',
    'J9299': 'Nivolumab (Opdivo)',
    'J9022': 'Atezolizumab (Tecentriq)',
    'J9173': 'Durvalumab (Imfinzi)',
    // Oncology - Chemotherapy
    'J9035': 'Bevacizumab (Avastin)',
    'J9355': 'Trastuzumab (Herceptin)',
    'J9306': 'Pertuzumab (Perjeta)',
    'J9041': 'Bortezomib (Velcade)',
    'J9228': 'Ipilimumab (Yervoy)',
    // Oncology - Targeted Therapy
    'J9025': 'Azacitidine (Vidaza)',
    'J9034': 'Bendamustine (Treanda)',
    'J9039': 'Blinatumomab (Blincyto)',
    // Supportive Care
    'J2505': 'Pegfilgrastim (Neulasta)',
    'J1442': 'Filgrastim (Neupogen)',
    'J0897': 'Denosumab (Xgeva)',
    'J2796': 'Romiplostim (Nplate)',
    // Rheumatology
    'J0129': 'Abatacept (Orencia)',
    'J0135': 'Adalimumab (Humira)',
    'J1745': 'Infliximab (Remicade)',
    'J2182': 'Mepolizumab (Nucala)',
    // Other Specialty
    'J0178': 'Aflibercept (Eylea)',
    'J2778': 'Ranibizumab (Lucentis)',
    'J1300': 'Eculizumab (Soliris)',
  }

  return drugMap[drugCode] || drugCode
}

/**
 * Returns human-readable description for CPT modifier codes.
 *
 * Modifiers provide additional information about services:
 * - Anatomical location (LT, RT, 50)
 * - Service circumstances (25, 59)
 * - Provider qualification (AS, GC)
 * - Drug administration (JW, JZ)
 *
 * In production, this would query CMS modifier definitions.
 */
function getModifierDescription(modifierCode: string): string {
  const modifierMap: Record<string, string> = {
    // Anatomical Modifiers
    'LT': 'Left side',
    'RT': 'Right side',
    '50': 'Bilateral procedure',
    'E1': 'Upper left eyelid',
    'E2': 'Lower left eyelid',
    'E3': 'Upper right eyelid',
    'E4': 'Lower right eyelid',
    'FA': 'Left hand, thumb',
    'F1': 'Left hand, 2nd digit',
    'TA': 'Left foot, great toe',
    // Service Circumstance Modifiers
    '22': 'Increased procedural services',
    '23': 'Unusual anesthesia',
    '24': 'Unrelated E/M during postop period',
    '25': 'Significant, separately identifiable E/M',
    '26': 'Professional component',
    '27': 'Multiple outpatient E/M encounters',
    '47': 'Anesthesia by surgeon',
    '51': 'Multiple procedures',
    '52': 'Reduced services',
    '53': 'Discontinued procedure',
    '54': 'Surgical care only',
    '55': 'Postoperative management only',
    '56': 'Preoperative management only',
    '57': 'Decision for surgery',
    '58': 'Staged or related procedure',
    '59': 'Distinct procedural service',
    '76': 'Repeat procedure, same physician',
    '77': 'Repeat procedure, different physician',
    '78': 'Unplanned return to OR',
    '79': 'Unrelated procedure during postop period',
    // Drug Administration Modifiers
    'JW': 'Drug amount discarded/not administered',
    'JZ': 'Zero drug amount discarded',
    // NCCI/Bundling Modifiers
    'XE': 'Separate encounter',
    'XP': 'Separate practitioner',
    'XS': 'Separate structure',
    'XU': 'Unusual non-overlapping service',
    // Provider Modifiers
    'AS': 'Assistant at surgery (PA/NP/CNS)',
    'GC': 'Resident under teaching physician',
    'GE': 'Resident without teaching physician',
    // ASC Modifiers
    'SG': 'ASC facility service',
    '73': 'Discontinued outpatient procedure prior to anesthesia',
    '74': 'Discontinued outpatient procedure after anesthesia',
    // Telehealth
    '93': 'Synchronous telemedicine service',
    '95': 'Synchronous telemedicine via real-time audio/video',
    'GT': 'Interactive audio/video telehealth',
  }

  return modifierMap[modifierCode] || `Modifier ${modifierCode}`
}

/**
 * Determines if a modifier is required for a clean claim.
 *
 * Modifier requirements depend on:
 * - CPT code (some procedures require specific modifiers)
 * - Payer rules (Medicare vs commercial requirements differ)
 * - Service context (multiple procedures, bilateral, etc.)
 *
 * In production, this would query payer-specific billing rules
 * from the CMS NCCI edits database and payer portals.
 */
function isModifierRequired(modifierCode: string, cptCode: string): boolean {
  // JW modifier required when drug wastage occurs (CMS requirement)
  // This prevents audits and ensures accurate drug utilization tracking
  if (modifierCode === 'JW') {
    // J-codes (drugs) should have JW or JZ modifier per CMS billing guidelines
    return cptCode.startsWith('J')
  }

  // 59/X{EPSU} modifiers - required when unbundling NCCI edits
  // These are typically suggested by the validation engine, not auto-required
  if (['59', 'XE', 'XP', 'XS', 'XU'].includes(modifierCode)) {
    return false
  }

  // 25 modifier - required for significant E/M on same day as procedure
  // Depends on whether E/M is billed with procedure
  if (modifierCode === '25') {
    return cptCode.startsWith('99')
  }

  // Default: modifiers are suggestions, not requirements
  return false
}
